---
title: Secrets Uncovered
date: 2024-10-20T17:03:39-07:00
draft: false
---

* Fennec and Mouse
- Found a bunch of safes and stuff

* Lab
- Locked doors
- No locks or keyholes
- Trying to break: Room gets warmer, holo-Margaret appears
- Interface with holo-Margaret: Eyes flash yellow and vanishes, Seams open up in the ground, it begins to shift. Mechanical whirring
- A stained-glass hands grips the edge of the hole in the ground.
- Solar-glass golem
- We fought it. It apparently blew up.

** Lab for real
- Margaret remembered something, was able to get us in.
- Lots of advanced alchemy stuff, even on a 29 I don't know it but I've seen some of it in my colleagues' work.
- Massive amounts of magical resources
- 7-foot vats, one containing a corpse with tubes running in/out.
- Lots of blood samples, stacks of notes.
- Religious and alchemical texts
- Painting: Margaret and another women
- Corpse: Vaguely Dhampyr. So vampire-descendant, approximately. But not quite a Dhampyr.
- The corpse is "whole" according to Zunni, i.e alive
- Painting: Sadness, associated with Margaret
- We found the storehouse, and also Margaret's notebook
- Fennec found a cleansing crystal, a magical conduit. The crystal was in a vat with a tube feeding into the corpse-vat
- So it was one of the components of her attempt to purify/cure vampires.
- Margaret looked through her notebook, and reactivated the experiment!
- Alex is the person in the vat, Margaret brought them back and they seem like fine?
- They waved to Fennec
- Color returned to their face after some blood(?) transfusion
- We made it out, we're now fleeing the gargantua and bat is trying to keep pace with us.
