---
title: Stories of Lastwall
date: 2024-09-22T15:12:34-07:00
draft: false
---

* Return
- Margaret is better than the Witch at plague-curing
- Mosquito Witch is happy with us
- She draws Fennec's blood, carves it into runes in the air.
- The runes let her divine Fennec's past (full name), and present (his wife is in danger)
- Rune language is ancient pre-existing. Lets someone read the present, like reading bones
- Petey can understand it (when augmented by Zuni)
- The Mosquito Witch isn't a manuscript, just a magical "encoding" of images and events. So the witch is experiencing visions of past/present/future.
- The runes aren't the primary information career.
- The Mosquito Witch has ADHD
** Grandmother Spider
- Does have followers
- Hidden sanctuaries
- Especially in the Mwangi Expanse
- The village with the blood avatar mostly had religious symbols devoted to Gazrah, god of nature/wind/waves.
- One personal trinket - suggests worship of grandmother spider. So there were adherents there, who were presumably purged
- So a blood avatar was installed there, and another was installed in Shimmerford. A plot.
* Loredump
- Margaret figured out a cure,
- Had it redacted from her memory
- She figured out a cure, a way to reject Zura's gift
- As punishment, Kiordan chose her to become the avatar of Zura
- She escaped before that was completed
- All but two lost their memory of Margaret and of the cure
- Then later, Margaret had her own memories erased, just before Kiordan sent out a search party for her. Presumably she escaped, had memories redacted (willingly or not).
- Given the patterns being pointed out, it seems that the memory-erasures we're learning about all come from the same source.
- So almost certainly all are the slate
- We did the mind-dive thing.
- One word: "Lastwall".
** Lastwall
- It blew up eleven years ago.
- Destroyed by the Lich-king Tarbafon
- Now he rules over the remains, calls it the Gravelands
- Tarbafon's soulcage is guarded by the god of undeath on a separate plane
- Initially Lastwall was built around his prison
- Tarbafon (the whispering tyrant) duelled a living god 4000 years ago. So he doesn't give a shit about Kiordan.
- Geb (the necromancer himself) has zero respect for Zura, thinks she's a wannabe god.
** Drannith
- "Drannith is an opportunist"
- Our faith in her is not misplaced (at time of speaking), but be careful
- She's more in this to spite Kiordan than to help us.
- Think about her. And about Womble.
*  Nomble
- Nomble is waiting when we return to the house
- Genevieve gets into an argument about how the House knows geography
- Nomble wants to know where we're going
* Next Stop
- Grace, a town in Ustalov
- Just outside the gravelands
* New Next Stop
- Steyr, to save Fennec's wife
